// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "CANTalon.h"
#include "LiveWindow/LiveWindow.h"

#include "DoubleSolenoid.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::chassisRightDrive;
std::shared_ptr<CANTalon> RobotMap::chassisRightDrive2;
std::shared_ptr<CANTalon> RobotMap::chassisLeftDrive1;
std::shared_ptr<CANTalon> RobotMap::chassisLeftDrive2;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

std::shared_ptr<DoubleSolenoid> RobotMap::pneumatic;


void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    chassisRightDrive.reset(new CANTalon(2));
    
    chassisRightDrive2.reset(new CANTalon(3));
    
    chassisLeftDrive1.reset(new CANTalon(5));
    
    chassisLeftDrive2.reset(new CANTalon(4));
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    pneumatic.reset(new DoubleSolenoid(0,0,7));



}
